### ISSUE TITLE
Not really an issue, but a comment

### ISSUE THREAD

**Issue by GrouchyGaijin** [tobixen/calendar-cli#10]
Firstly, thank you for developing this.  I have been looking for a good cli calendar replacement since I quit using Google Calendar.

1.  I have the script working and can add events to my calendar which is hosted at fruux.com.
Adding an event by typing in the really long calendar URL is a bit cumbersome, is it possible to set a default calendar url and a default task url in the config file?

2. In my config file I set the timezone to my local time, Europe/Stockholm.  How do I add times to new events?  It seems that my events always end up as being from 02.00.

**Comment by tobixen** [comment]
Hi,

The cli is rather cumbersome at the moment, and the interface is also not very stable yet.  I'm planning to make it easier (short options, etc), but it needs some proper planning first.

There is support for multiple configuration sections as of today, and I have also just added support for one section to inherit another (did I document that?  probably not?).

I'm currently using this (admittedly, ugly) shell construct to list my agenda:

    for section in pp seb house default work ; do ./calendar-cli.py --config-section $section calendar agenda  --agenda-days 20; done | sort ; for section in seb house default work-tasks pp-tasks ; do echo $section; ./calendar-cli.py --config-section $section todo --limit 10 list

And here is my ~/.config/calendar.conf:

    {
    "default": {
        "caldav_pass": "hunter2", 
        "caldav_url": "http://calendar.bekkenstenveien53c.oslo.no/caldav.php/", 
        "caldav_user": "tobias"
    }, 
    "seb": {
        "inherits": "default",
        "calendar_url": "sebastian/calendar"
    }, 
    "house": {
        "inherits": "default",
        "calendar_url": "house/calendar"
    }, 
    "work": {
        "caldav_pass": "hunter2"
        "caldav_url": "https://zimbra.redpill-linpro.com/dav/", 
        "caldav_user": "tobias@redpill-linpro.com"
    },
    "work-tasks": {
        "inherits": "work",
        "calendar_url": "tobias@redpill-linpro.com/Tasks/"
    },
    "pp": {
        "caldav_pass": "hunter2", 
        "caldav_url": "https://mail.piratpartiet.no/dav/", 
        "caldav_user": "tobias@piratpartiet.no"
    },
    "pp-tasks": {
        "inherits": "pp",
        "calendar_url": "tobias@piratpartiet.no/Tasks/"
    }
    }

**Comment by tobixen** [comment]
Forgot to write, I will add support for --calendar-name soon, that will also make it a bit easier.

I think I have neither tested configuration of time zone in the config file, nor tested much to add calendar events with only date and no time.  If you add only the date and the event gets 00:00 UTC as start time (02:00 Stocholm summer time),  that's a bug.  I'll add a separate issue for that.

Here is an example from the test script:

echo "## Attempting to add a past event at 2010-10-11 20:00:00, CET, 3h duration"
calendar_cli calendar add '2010-10-11 20:00:00+01:00+3h' 'testing testing'
