### ISSUE TITLE
test_cal.py no longer usable (since splitting plann and calendar_cli)

### ISSUE THREAD

**Issue by fauxmight** [tobixen/calendar-cli#105]
If I am reading correctly, it appears that the bulk of the tests in `test_cal.py` are using the `parse_timespec()` function from `cal.py`.

As `cal.py` was split out to `plann`, `parse_timespec` is no longer importable and these tests are no longer usable.

If I am wrong, let me know.
If I am not, let me know and I will push a PR with the affected tests removed from `test_cal.py`.

I am writing a `calendar-cli-git` PKGBUILD for AUR and after chasing down this issue I found that I currently just need to have testing completely disabled in the PKGBUILD.

@tobixen feedback is welcome.

**Comment by tobixen** [comment]
A PR is most welcome.  Sorry for the breakage.

**Comment by fauxmight** [comment]
Resolved by #106
