### ISSUE TITLE
Why "cal calendar add" does not sync new event with server?

### ISSUE THREAD

**Issue by dmikushin** [tobixen/calendar-cli#110]
Due to the lack of documentation, I'm not able to understand why `cal calendar add` does not automatically upload the event to the server. With `cal calendar agenda` I'm able to see the added event in the list, but it is never added into the CalDAV server and does not become available to the other clients. What am I missing?

**Comment by tobixen** [comment]
calendar-cli does not hold any local storage.  If you can see it with `cal calendar agenda`, then it is added to the server.

**Comment by tobixen** [comment]
So the question is rather: why does not your other clients see the event?

**Comment by dmikushin** [comment]
Thanks @tobixen , you are right. By some reason it takes the two other clients (Android via DAVx5 and iOS standard CalDAV) more than 30 minutes to get the calendar updates synchronized. I've unlocked the screens to make sure they come out of sleep and able to connect to the internet. I use Radicale as a CalDAV server. Appreciate your advice!
