### ISSUE TITLE
Bug: UnboundLocalError when using --nocaldav

### ISSUE THREAD

**Issue by gfaieta** [tobixen/calendar-cli#13]
Variable `caldav_conn` is referenced without being defined if `--nocaldav` option is used (at the bottom of `calendar-cli.py`)

**Comment by tobixen** [comment]
I've attempted fixing this.

Unfortunately we're missing test code to cover this.  It would be very nice with some kind of unittests utilizing the --nocaldav option.  I've attempted to create a run-through functional test script in the test directory, but it's not covering --nocaldav.
