### ISSUE TITLE
KeyError: 'default' in File "./bin/calendar-cli.py", line 500, in config_section

### ISSUE THREAD

**Issue by muelli** [tobixen/calendar-cli#18]
```
>./bin/calendar-cli.py  -h
Traceback (most recent call last):
  File "./bin/calendar-cli.py", line 665, in <module>
    main()
  File "./bin/calendar-cli.py", line 552, in main
    defaults = config_section(config, args.config_section)
  File "./bin/calendar-cli.py", line 500, in config_section
    if 'inherits' in config[section]:
KeyError: 'default'
```

**Comment by tobixen** [comment]
fixed in the dev branch.  I hope to make a new release soon.

@ChangeTip, give 2000 bits to muelli

**Comment by changetip** [comment]
Hi @muelli, @tobixen sent you a tip worth 2000 bits ($0.79), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/936285)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
