### ISSUE TITLE
Odd interaction with DAViCal

### ISSUE THREAD

**Issue by zepalmer** [tobixen/calendar-cli#21]
I'm running a DAViCal server in which my user account has multiple associated calendars (specifically, "teaching", "research", and "administrative").  When I use `calendar-cli` to create a TODO and provide the URL of any calendar, the item is added to the research calendar.  I would assume this to be a bug in DAViCal, but both my Android calendar sync client (DAV Droid) and my laptop's client (Thunderbird Lightning) have no trouble adding tasks to specific calendars.

I've checked the configuration parsing and `calendar-cli` is indeed passing the right URL to the underlying calendar library, but I thought I'd file this issue so that it's know that it exists (even if the problem turns out to be an underlying dependency instead of some way that `calendar-cli` is using it).

**Comment by tobixen** [comment]
I'm also using DAViCal FWIW.

Unfortunately I haven't had time to look much into neither calendar-cli nor the python caldav library for quite some time.  That's really a shame.

**Comment by tobixen** [comment]
Sorry for the delay on this.  Do you observe this behaviour with the latest dev-branches of calendar-cli and caldav library?

**Comment by tobixen** [comment]
I'm also using DAViCal, and I don't seem to have any issues.  Do you have more details?  Can you include steps to reproduce?

**Comment by zepalmer** [comment]
Sorry I haven't been very responsive on this!  This may not be a DAViCal problem specifically; I'm not sure.  I recently found a workaround that might provide more information about what's going on.

I have my `.config/calendar.conf` set up like so:

```
{
    "me": {
        "caldav_user": "zepalmer", 
        "caldav_pass": "redacted"
    },
    "default": {
        "inherits": "teaching"
    },
    "teaching": {
        "caldav_url": "https://myserver.com:8443/caldav.php/zepalmer/teaching", 
        "inherits": "me" 
    },
    "research": {
        "caldav_url": "https://myserver.com:8443/caldav.php/zepalmer/research", 
        "inherits": "me" 
    },
    "administrative": {
        "caldav_url": "https://myserver.com:8443/caldav.php/zepalmer/administrative", 
        "inherits": "me" 
    }
}
```

I have a script that runs multiple calls to `calendar-cli.py`.  For instance, here are some of the calls generated this semester:

```
calendar-cli.py todo add --set-dtstart 2017-01-24 13:00:00 --set-due 2017-01-24 17:00:00 --alarm 0s Post lecture materials and video: 01-24
calendar-cli.py todo add --set-dtstart 2017-01-21 00:00:00 --set-due 2017-01-24 00:00:00 --alarm 0s Lecture notes: 01-24
calendar-cli.py todo add --set-dtstart 2017-01-26 13:00:00 --set-due 2017-01-26 17:00:00 --alarm 0s Post lecture materials and video: 01-26
calendar-cli.py todo add --set-dtstart 2017-01-23 00:00:00 --set-due 2017-01-26 00:00:00 --alarm 0s Lecture notes: 01-26
...
```

If I generate the calls above, the TODOs are **always** added to my research calendar and not my teaching calendar (even though that's set to be the default in my configuration file).  However, I've discovered that the following commands do the *right* thing:

```
calendar-cli.py --calendar-url https://myserver.com:8443/caldav.php/zepalmer/teaching todo add --set-dtstart 2017-01-24 13:00:00 --set-due 2017-01-24 17:00:00 --alarm 0s Post lecture materials and video: 01-24
calendar-cli.py --calendar-url https://myserver.com:8443/caldav.php/zepalmer/teaching todo add --set-dtstart 2017-01-21 00:00:00 --set-due 2017-01-24 00:00:00 --alarm 0s Lecture notes: 01-24
calendar-cli.py --calendar-url https://myserver.com:8443/caldav.php/zepalmer/teaching todo add --set-dtstart 2017-01-26 13:00:00 --set-due 2017-01-26 17:00:00 --alarm 0s Post lecture materials and video: 01-26
calendar-cli.py --calendar-url https://myserver.com:8443/caldav.php/zepalmer/teaching todo add --set-dtstart 2017-01-23 00:00:00 --set-due 2017-01-26 00:00:00 --alarm 0s Lecture notes: 01-26
...
```

Note the use of `--calendar-url` here to explicitly set the calendar URL (even though it is explicitly set in `.config/calendar.conf`).  Is it possible that I've messed up the format for that configuration file somehow?  Does `calendar-cli.py` validate the contents of that file at all?

Thank you!

**Comment by tobixen** [comment]
I think I see a problem here; you should use calendar_url and not caldav_url in the config file.

caldav_url should be just https://myserver.com:8443/caldav.php/ - while the calendar_url should specify which calendar, so "https://myserver.com:8443/caldav.php/zepalmer/research" is correct for the calendar url.

As for validation of the config file ... I believe that's handled by argparse.  Those are the relevant lines:

    defaults = config_section(config, args.config_section)
    (...)
    parser.set_defaults(**defaults)

meaning anything that goes as command line options can also be passed in the config file.
