### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by rjc** [tobixen/calendar-cli#23]
Hi,

I couldn't find any information regarding the license your program is under - some might not be able to use your software until this is resolved.

Personally, I'd recommend an [ISC-style license](https://opensource.org/licenses/ISC).

Regards,

Raf

**Comment by tobixen** [comment]
__license__ = "GPLv3+" it says in the .py-file, so I guess I'll stick with that.

**Comment by rjc** [comment]
Hi,

    __license__ = "GPLv3+"

is just a variable and doesn't actually say that the content of that file is under GPLv3+ - that's [true for any license, not just GPLv3+](https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile).

Cheers,

Raf

**Comment by tobixen** [comment]
Can you check if commit 9de70bc6c80d5ad7fb330adabed343a93af83658 is sufficient?

**Comment by rjc** [comment]
Hi,

Yes, looks good - thank your for clarifying it.

Cheers,

Raf
