### ISSUE TITLE
calendar-cli on PyPi

### ISSUE THREAD

**Issue by slavkoja** [tobixen/calendar-cli#24]
There is a `calendar-cli` on the [PyPi](https://pypi.python.org/pypi/calendar-cli/), it seems as related (_gcalendar_), but not the same apps and this can be confusing for the users (include me, for while). IMO will be good at least to mention it in README, to prevent confusing, or ,if you are willing, to rename the project.

**Comment by tobixen** [comment]
Oh darn :-(

**Comment by tobixen** [comment]
I don't want to rename the project, my project has existed for a lot longer than the pypi calendar-cli, and since the other calendar-cli is a google-client I think the other project rather should be renamed to gcalendar-cli.

**Comment by slavkoja** [comment]
i agree with no rename, it was only one of solutions ;-) I am not owner of this project, i did only look, if your project is installable via pip...

**Comment by tobixen** [comment]
Should probably try to talk with the maintainers of the pypi project and gently suggest them to rename their project to gcalendar-cli.  I'm not just sure if I have sufficiently good diplomacy skills to do so.

Maybe the problem will resolve itself.  We'll see if their calendar-cli is kicking and alive in some few years or if it's abandonware.  And vice-versa :-)

I didn't consider pypi as I consider this to be a stand-alone command-line utility and not a python library.

**Comment by guyzmo** [comment]
pypi is quite often used to also install CLI tools, and some package managers (like brew) refuse to install python packages.

**Comment by slavkoja** [comment]
it seems as bigger problem than i initially think, because ``pip`` offers the ``callendar-cli`` update:
```
pip list --outdated
...
calendar-cli (0.0.0) - Latest: 0.1.3 [sdist]
```

**Comment by guyzmo** [comment]
maybe could we discuss with the author of the other `calendar-cli` so he could rename his `gcalendar-cli` or something like that, which would make much more sense?

**Comment by mogproject** [comment]
Hello! I was the author of `calendar-cli` on PyPI. I just renamed mine to `gcalendar-cli` so that it does not conflict with yours.

Thank you.

**Comment by tobixen** [comment]
Thanks a bunch!

**Comment by reubano** [comment]
When will this version be available on pypi?
