### ISSUE TITLE
Kolab Now not working

### ISSUE THREAD

**Issue by nicorikken** [tobixen/calendar-cli#30]
I wanted to try out `calendar-cli`, which looks very promising. Yet I cannot get it to work with my CalDav calendars in Kolab Now. I use them successfully with DavDroid, Evolution and Thunderbird, so I think this ought to work as well.

Kolab has a variety of endpoints to use, as also documented: https://kolabnow.com/clients/others#carddav-and-caldav-settings
- `https://apps.kolabnow.com`
- `https://apps.kolabnow.com/calendars`
- `https://apps.kolabnow.com/calendars/<account_mail_address>`
- `https://apps.kolabnow.com/calendars/<account_mail_address>/<unique_id_per_calendar>`

When I try to connect, I get returned an error: `Exception: The CalDAV server you are using has a problem with path handling.`
If I fail to provide a password I get a `caldav.lib.error.AuthorizationError: ... reason 'Unauthorized'` error, so it seems it is failing at some of the latter stages.
I tried both the calendar and task lists.

I could not easily search in the bitbucket code of the underlying library. Is that the one I should be looking into to resolve this issue? Are there ways in which I can debug this issue?

**Comment by tobixen** [comment]
The caldav python library has moved from bitbucket to github, you'll find it at https://github.com/python-caldav/caldav.  Make sure you're using the latest version of it, and re-raise the issue at the caldav repository.

I'm the de-facto maintainer of the python caldav library, so I will eventually be doing research if needed.  I don't have time to look into kolab right now, but it would help a lot if I you could provide me with some login credentials to some  for testing, or eventually point me to a working docker image that I can use for testing.

**Comment by tobixen** [comment]
Great, they actually have a test login in their cloud solution.  I can for sure use that, but I don't have time right now.

I believe https://apps.kolabnow.com/ should be the appropriate caldav URL.

**Comment by nicorikken** [comment]
Thanks for the info so far. I'll check to make sure I'm up to date on the library. That should be version 0.5.0 then. Is there a way I can get a debug output to help debugging? Or do you know where in the sourcecode of caldav I should be looking for this error?

**Comment by tobixen** [comment]
I was wrong about the test login.  "test@kolabnow.com" seems to be just a placeholder in the documentation, " please make sure to replace test@kolabnow.com with your actual username"

Kolab exists as a docker image, I may be able to test it from there.

**Comment by tobixen** [comment]
That kolab docker image was apparently broken, so no luck there.

I can see that the error message "The CalDAV server you are using has a problem with path handling." comes from caldav/objects.py, method DAVObject.get_properties.  I did not write up that error myself, and I'm not sure what's wrong here.  What I eventually would do, I'd throw in "import pdb; pdb.set_trace()" right before the exception raising, check what we sent to the server and what we're getting back, and then eventually read the RFC to try to understand if the problem is at the client side or server side.

**Comment by nicorikken** [comment]
Thanks for the details. I tried it. It think I know where the issue originates from:
```
(Pdb) properties
{'/calendars/nico@nicorikken.eu/': {'{DAV:}current-user-principal': '/principals/nico%40nicorikken.eu/'}}
(Pdb) path
u'/calendars/nico%40nicorikken.eu/'
```
So clearly the URL encoded path is the issue here. This is default at Kolab: [client settings](https://kolabnow.com/clients/others#carddav-and-caldav-settings).
Changing the User to URL-encoded results in an 'unauthenticated' error.
Changing the URL to non-URL-encoded, does not fix the issue:
```
(Pdb) properties
{'/principals/nico@nicorikken.eu/': {'{urn:ietf:params:xml:ns:caldav}calendar-home-set': '/calendars/nico%40nicorikken.eu/'}}
(Pdb) path
'/principals/nico%40nicorikken.eu/'
```
Somehow the URL encoding should be resolved.

**Comment by tobixen** [comment]
I don't have much time to look into this right now ... but I do use calendar-cli towards a zimbra-calendar, where my username is my email address, with the at-sign.  That works for me.

**Comment by nicorikken** [comment]
I want to try to circumvent this particular key-match issue, by selecting the single key, or normalizing the string to be either URL-encoded or non-URL-encoded. Hopefully this is the only issues, and the rest will work as it should.

**Comment by nicorikken** [comment]
I circumvented the issue seemingly successful:
`rc = properties.values()[0]`
Then I hit an issue in the `calendar-cli`:
```
$ calendar-cli.py todo list
Traceback (most recent call last):
  File "/usr/local/bin/calendar-cli.py", line 858, in <module>
    main()
  File "/usr/local/bin/calendar-cli.py", line 855, in main
    ret = args.func(caldav_conn, args)
  File "/usr/local/bin/calendar-cli.py", line 579, in todo_list
    tasks = todo_select(caldav_conn, args)
  File "/usr/local/bin/calendar-cli.py", line 476, in todo_select
    tasks = find_calendar(caldav_conn, args).todos()
  File "/usr/local/bin/calendar-cli.py", line 118, in find_calendar
    return caldav.Principal(caldav_conn).calendars()[0]
IndexError: list index out of range
```
I'll try some more to hopefully resolve this issue as well.
