### ISSUE TITLE
Time stamp in events

### ISSUE THREAD

**Issue by sfg** [tobixen/calendar-cli#31]
Hi, I recently installed calendar-cli and it looks promising! However, display calendar agendas (from Nextcloud Server) shows the wrong event time, e.g. The event is scheduled for 10:00 o'clock in Nextcloud, calendar-cli shows 8:00 o'clock. Setting the timezone in config file to 

"timezone": "Europe/Berlin"

does not work. Any suggestions? Thanks, Sven

**Comment by tobixen** [comment]
I'd like to see how the timestamp looks in the ics.  Try this:

./calendar-cli.py --icalendar calendar agenda

and see if you can find the timestamps there.

I see that in my calendar the DTSTART is set up without timezone.  I suspect that DTSTART is set up in UTC-time in your calendar, and that the code for converting to localtime is either missing or buggy.

**Comment by sfg** [comment]
thanks for your comment! Indeed, DTSTART has the wrong time and has no timezone. For example, an event scheduled for 17:00 o'clock has DTSTART:

DTSTART:20170709T150000Z

Nextcloud uses Sabre. I file a report about that issue to Nexcloud mailing list.

**Comment by tobixen** [comment]
No, no, this is correct.  Z means UTC.

**Comment by tobixen** [comment]
The bug is in calendar-cli, not in Sabre.

**Comment by sfg** [comment]
sorry, I misunderstand you.

**Comment by tobixen** [comment]
Oh, sorry for the lack of feedback here.  I believe the problem should be solved, if using the newest version of the python-caldav library.
