### ISSUE TITLE
Crash for older start time etc.

### ISSUE THREAD

**Issue by tfinke** [tobixen/calendar-cli#32]
Hi, 

I highly appretiate your project, since a command line interface to CalDav is urgently needed.

Unfortunately calendar-cli.py keeps crashing for many operations, e.g.:
- "calendar-cli.py calendar agenda --from-time 2017-04-01 --to-time 2017-07-01" works, 
  but changing from-time to 2017-03-01 yields a crash:

  
Traceback (most recent call last):
  File "/usr/local/bin/calendar-cli.py", line 866, in <module>
    main()
  File "/usr/local/bin/calendar-cli.py", line 863, in main
    ret = args.func(caldav_conn, args)
  File "/usr/local/bin/calendar-cli.py", line 436, in calendar_agenda
    events_ = find_calendar(caldav_conn, args).date_search(dtstart, dtend)
  File "/usr/lib/python2.7/site-packages/caldav/objects.py", line 510, in date_search
    Event(self.client, url=self.url.join(r), data=results[r][cdav.CalendarData.tag], parent=self))
  File "/usr/lib/python2.7/site-packages/caldav/objects.py", line 724, in __init__
    self.data = data
  File "/usr/lib/python2.7/site-packages/caldav/objects.py", line 801, in _set_data
    self._instance = vobject.readOne(to_unicode(self._data))
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 1153, in readOne
    allowQP))
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 1125, in readComponents
    component.transformChildrenToNative()
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 674, in transformChildrenToNative
    child.transformChildrenToNative()
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 673, in transformChildrenToNative
    child = child.transformToNative()
  File "/usr/lib/python2.7/site-packages/vobject/base.py", line 185, in transformToNative
    return self.behavior.transformToNative(self)
  File "/usr/lib/python2.7/site-packages/vobject/icalendar.py", line 1386, in transformToNative
    raise ParseError("DURATION must have a single duration string.")
vobject.base.ParseError: At line 9: DURATION must have a single duration string.

- also a simple "calendar-cli.py calendar agenda" yields:

Traceback (most recent call last):
  File "/usr/local/bin/calendar-cli.py", line 866, in <module>
    main()
  File "/usr/local/bin/calendar-cli.py", line 863, in main
    ret = args.func(caldav_conn, args)
  File "/usr/local/bin/calendar-cli.py", line 436, in calendar_agenda
    events_ = find_calendar(caldav_conn, args).date_search(dtstart, dtend)
  File "/usr/lib/python2.7/site-packages/caldav/objects.py", line 507, in date_search
    results = self._handle_prop_response(response=response, props=[cdav.CalendarData()])
  File "/usr/lib/python2.7/site-packages/caldav/objects.py", line 145, in _handle_prop_response
    for r in response.tree.findall('.//' + dav.Response.tag):
AttributeError: 'NoneType' object has no attribute 'findall'

My .config looks like:

{
    "default": {
        "caldav_url": "http://my-davical/caldav.php/", 
        "calendar_url": "my/calendar", 
        "caldav_user": "my",
        "caldav_pass": "XXXXXX" 
    },
    "all": {
        "caldav_url": "http://my-davical/caldav.php/", 
        "calendar_url": "all/calendar", 
        "caldav_user": "all",
        "caldav_pass": "XXXXXX" 
    }
}

Evolution and Lightning display proper calendar entries for both sections. 

To be honest, nearly every invocation of calendar-cli.py crashes for me. 
I am running Python 2.7.12 on an OpenSuSE 42.1.

What would be my mistake? 
Is there a chance to catch errors before Python starts it's error handling? 

Best regards

T. Finke

**Comment by tobixen** [comment]
I'm at vacation, not sure I'll get time to look into it this week.

It sounds a bit like module version incompatibility problems.  Could you check what versions of the python caldav library and vobject library you're using, as well as the version of the calendar-cli library?

**Comment by tfinke** [comment]
Dear Tobias,

On Tue, Jul 25, 2017 at 02:17:16AM -0700, Tobias Brox wrote:
> I'm at vacation, not sure I'll get time to look into it this week.

don't worry - have a nice vacation first. 

> It sounds a bit like module version incompatibility problems.  Could
> you check what versions of the python caldav library and vobject
> library you're using, as well as the version of the calendar-cli
> library?

pip says:
'vobject: 0.9.5', 
'caldav: 0.5.0'

calendar-cli.__version__ = "0.11.0"
(I think my colleague got it from github last week).


If there are any other information I could prepare, please let me
know.


Thanks for your project and best regards



Torsten






-- 
------------------------------------------------------------------------
Dr.-Ing. Torsten Finke
torsten.finke@igh.de
Tel.: +49 201 / 36014-17

Ingenieurgemeinschaft IgH
Gesellschaft für Ingenieurleistungen mbH
Heinz-Bäcker-Str. 34
D-45356 Essen

Amtsgericht Essen HRB 11500
USt-Id.-Nr.: DE 174 626 722
Geschäftsführung: 
- Dr.-Ing. T. Finke, 
- Dr.-Ing. W. Hagemeister
Tel.: +49 201 / 360-14-0
http://www.igh.de

GnuPG-Key: 1024D/8F2300D8
Fingerprint: B929 7FA5 4D2E E9B6 C55C  8A0B 7DF4 86E9 8F23 00D8
------------------------------------------------------------------------

**Comment by tobixen** [comment]
Perhaps related to #33.

**Comment by tfinke** [comment]
Dear Tobias, 

On Tue, Aug 29, 2017 at 02:54:29AM -0700, Tobias Brox wrote:
> Perhaps related to #33.

I doubt it. The installed script (calendar-cli.py) starts with:

#!/usr/bin/python2


Also it produces the nice error message you mentioned. 

Could one help to migrate the tool to python3?


Best regards


Torsten Finke



-- 
------------------------------------------------------------------------
Torsten Finke
torsten.finke@igh.de
Ingenieurgemeinschaft IgH
Gesellschaft für Ingenieurleistungen mbH
D-45356 Essen
------------------------------------------------------------------------

**Comment by tobixen** [comment]
Oh, sorry for the very untimely response to this.  I suspect the caldav server was serving the client some icalendar object that either wasn't RFC-compliant or that the vobject library couldn't handle for other reasons.  I suspect there is no point digging more into it now, nearly three years later ...
