### ISSUE TITLE
Python3-compatibility

### ISSUE THREAD

**Issue by tobixen** [tobixen/calendar-cli#33]
When calendar-cli was created, the caldav-library only existed in python2-version, and it was further dependent on vobject, which also only existed in python2-version.  Those obstacles have been solved now.  "python2" is still hardcoded in the script though.

Even though "python2" is hardcoded in the script, when the script is installed through setup.py using python3, running the installed "calendar-cli" may invoke python3.  The script has not been thoroughly tested under python3.  It's needed to do quite some testing.

One bug spotted so far, run the script without any parameters, and argparse will print out a nice error message and user instructions when parser.parse_args is run on line 838 and exit.  Under python3 this does not happen, and instead we get an ugly error on line 836 as func is undefined.

**Comment by sqozz** [comment]
Another issue spotted: calendar-cli.py makes use of raw_input (e.g. for --interactive-config) which is not available anymore in python3 (since input() now always returns a string)

**Comment by tobixen** [comment]
Would you care to write up a pull request? :-)

**Comment by sqozz** [comment]
Not right now but sounds possible ;) I'll come up with something - you want to be backward compatible to python2 i guess?

**Comment by tobixen** [comment]
Yes (at least until python2 is officially deprecated)

**Comment by tobixen** [comment]
This one is biting me now as I didn't bother installing python2 on this laptop :-)

**Comment by tobixen** [comment]
Apparently the subcommand stuff in argparse differs in python3

```
$ python2 ./calendar-cli 
usage: calendar-cli [-h] [--config-file FILE]
                    [--config-section CONFIG_SECTION] [--interactive-config]
                    [--version] [--nocaldav] [--icalendar]
                    [--timezone TIMEZONE] [--language LANGUAGE]
                    [--caldav-url URL] [--caldav-user USER]
                    [--caldav-pass PASS] [--caldav-proxy CALDAV_PROXY]
                    [--ssl-verify-cert SSL_VERIFY_CERT] [--debug-logging]
                    [--calendar-url CALENDAR_URL] [--ignoremethod]
                    {todo,journal,calendar} ...
calendar-cli: error: too few arguments

$ python3 ./calendar-cli
Traceback (most recent call last):
  File "./calendar-cli", line 925, in <module>
    main()
  File "./calendar-cli", line 922, in main
    ret = args.func(caldav_conn, args)
AttributeError: 'Namespace' object has no attribute 'func'
```

(one may argue that the problem is the way I'm hacking in the "func" argument - but anyway, without a subcommand, we should get some help-text)

**Comment by tobixen** [comment]
... and also, `calendar todo list` prints out b'description'

That's all I get to test now.  At least two problems to fix.

**Comment by heinrich-ulbricht** [comment]
Oh well Python 2 is no more.

https://www.python.org/doc/sunset-python-2/ ->

> Sunsetting Python 2
> We are volunteers who make and take care of the Python programming language. We have decided that January 1, 2020, was the day that we sunset Python 2. That means that we will not improve it anymore after that day, even if someone finds a security problem in it. You should upgrade to Python 3 as soon as you can.

Just fyi :) I'd suggest creating separate tickets for all spotted Python 3 incompatibilities so volunteers can jump on board focusing on fixing specific issues.

**Comment by tobixen** [comment]
Aargh!  The future is already here upon us!

> so volunteers can jump on board focusing on fixing specific issues.

That sounds rather optimistic to me, I don't expect there will be an army of volunteers helping me with this one.  Anyway, this should be prioritized, I should try to get out a 0.12-version that is more or less tested with python3, and then from version 1.0 I won't care more about python2-compatibility (though, will try to avoid breaking python2-compatibility deliberately for a while still ...)

**Comment by tobixen** [comment]
I'm running calendar-cli from python3 now, and "python2" has been replaced with just "python" in the script.  I'll close this issue as I haven't encountered other problems so far - and any new issues encountered will just be raised independently of this one.

I'm planning to do quite some testing during the next weeks, and hope to release 0.12 this month.
