### ISSUE TITLE
Add installation instructions to Readme

### ISSUE THREAD

**Issue by jd7h** [tobixen/calendar-cli#36]
Or make the instructions in install.md more clear.

**Comment by E3V3A** [comment]
It's a useless README without any screenshot, nor installation instrux... :(

**Comment by tobixen** [comment]
The INSTALL.md has been removed and the contents embedded in the README.  Documentation should be looked through and refreshed in general, and I've opened a new issue #65 for that.  I will not include any screenshots though.
