### ISSUE TITLE
%F fails on Windows

### ISSUE THREAD

**Issue by linxsorg** [tobixen/calendar-cli#37]
I just noticed that the default date format ``%F`` fails on Windows,
tested with Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32) and calendar-cli.py with ``__version__ = "0.11.0"``.

I replaced ``%F`` with its equivalent ``%Y-%m-%d`` on lines 797 and 847 and confirmed it works.
Hope this would be helpful. Thanks.

**Comment by tobixen** [comment]
Could you submit a pull request?

**Comment by linxsorg** [comment]
OK, I've just sent a pull request.

**Comment by tobixen** [comment]
thanks.

I should have a look into the travis setup if/when I get the time ... hm. :-)
