### ISSUE TITLE
RFC4791 and METHOD property

### ISSUE THREAD

**Issue by ymitsos** [tobixen/calendar-cli#39]
Hi,

I receive frequently calendar invitations that include a METHOD property. According to RFC4791, paragraph 4.1 this must not happen, if I understand correctly. 

The latter causes an exception like this:
```
aceback (most recent call last):
  File "./calendar-cli.py", line 866, in <module>
    main()
  File "./calendar-cli.py", line 863, in main
    ret = args.func(caldav_conn, args)
  File "./calendar-cli.py", line 183, in calendar_addics
    _calendar_addics(caldav_conn, c.to_ical(), uid, args)
  File "./calendar-cli.py", line 143, in _calendar_addics
    c.add_event(ics)
  File "~/.virtualenvs/calendar-cli/lib/python2.7/site-packages/caldav/objects.py", line 422, in add_event
    return Event(self.client, data = ical, parent = self).save()
  File "~/.virtualenvs/calendar-cli/lib/python2.7/site-packages/caldav/objects.py", line 718, in save
    self._create(self._instance.serialize(), self.id, path)
  File "~/.virtualenvs/calendar-cli/lib/python2.7/site-packages/caldav/objects.py", line 704, in _create
    raise error.PutError(r.raw)
caldav.lib.error.PutError: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>
  <s:message>Validation error in iCalendar: A calendar object on a CalDAV server MUST NOT have a METHOD property.</s:message>
</d:error>
```
Would you consider handling this exception and selectively ignoring it for this use-case?

**Comment by tobixen** [comment]
Sounds like Microsoft clients? :-)

My first thought is that this is outside the scope of calendar-cli and the 'addics' method; addics simply copies the ICS code verbatim to the server, and does not care much about the RFC as such.  However, if this is a widespread problem I think it may be an idea to add an exception here stripping the non-conforming lines from the ICS and warn about it through logging.

**Comment by ymitsos** [comment]
Indeed, most of the times it is Microsoft client. Recently, I received such an invitation from other web apps and hence I raise the issue.

**Comment by tobixen** [comment]
I've done a quick code review now, so I'm closing this issue :-)
