### ISSUE TITLE
Caldav-Request does not support SNI

### ISSUE THREAD

**Issue by bwurst** [tobixen/calendar-cli#43]
When I try to fetch my calendar, I get the following error:
[...]
  File "/usr/local/lib/python2.7/dist-packages/caldav/davclient.py", line 127, in propfind
    return self.request(url or self.url, "PROPFIND", props, {'Depth': str(depth)})
  File "/usr/local/lib/python2.7/dist-packages/caldav/davclient.py", line 227, in request
    r = requests.request(method, url, data=to_wire(body), headers=combined_headers, proxies=proxies, auth=auth, verify=self.ssl_verify_cert)
[...]
requests.exceptions.SSLError: hostname 'XXXXXX' doesn't match 'YYYYYY'

My server has a valid certificate when the client requests it via SNI. What can I do to get this working? Is there some option to turn off cert verification as a workaround?

**Comment by tobixen** [comment]
Huh ... SNI not working?  Well, I'd never ... I'm just using upstream libraries.

Yes, there is a workaround for skipping the ssl cert verification ... does "--ssl-verify-cert=no" help you?

**Comment by bwurst** [comment]
Oh, forgot that I'm still on Ubuntu 14.04 on this machine, so it's python 2.7.6 and that has a requests module that does not support SNI. Python 2.7.9 is required for that.
Seems like I'll have to get my ass up and upgrade the system. :)
But it would be nice if this was documented.

**Comment by bwurst** [comment]
Okay, upgraded Python from backports and this solves my issue, I can use it now.

Sorry for the noise and thanks a lot for this handy software!
