### ISSUE TITLE
ImportError: No module named tzlocal

### ISSUE THREAD

**Issue by Pupo1** [tobixen/calendar-cli#46]
When I try to start calendar-cli on Linux Mint 17 Qiana, I get the error "ImportError: No module named tzlocal".
I can fix this with "sudo pip install tzlocal", but I think the error should not happen at all. 
Having fixed the error, I run into the next error "ImportError: No module named icalendar". 
I can fix that with "sudo pip install icalendar", but most people would probably have given up there already. Having fixed that error, I run into the next error "ImportError: No module named caldav", which makes me think about trying khal instead. I was able to fix the error with "sudo pip install caldav", though.

**Comment by tobixen** [comment]
How did you install it?  Both icalendar and tzlocal is listed as requirements in the setup.py file

**Comment by Pupo1** [comment]
I think I didn't install it at all but just started calendar-cli.py

**Comment by tobixen** [comment]
I think that if following the instructions in INSTALL.md this shouldn't be an issue at all :-)

**Comment by tobixen** [comment]
Oh.  In setup.py, tzlocal is not installed when using python3, because with python3 "batteries are included".  So this is a bug, indeed.
