### ISSUE TITLE
--interactive crashes the program

### ISSUE THREAD

**Issue by muelli** [tobixen/calendar-cli#50]
```
Traceback (most recent call last):
  File "calendar-cli.py", line 904, in <module>
    main()
  File "calendar-cli.py", line 772, in main
    parser.set_defaults(**defaults)
UnboundLocalError: local variable 'defaults' referenced before assignment
```

**Comment by tobixen** [comment]
That code was written once, not covered by any test code, and never tested again ... probably the code around has changed a bit.

I'm really in a pinch now timewise, too much to do and too little time.  I've committed a very quick attempt on fixing it in the master branch and v0.11.0.dev branch, but it's not at all tested.

**Comment by tobixen** [comment]
Seems to work
