### ISSUE TITLE
Select todo ID for editing

### ISSUE THREAD

**Issue by tigexplorer** [tobixen/calendar-cli#51]
Hi, 
very interesting project.

I need little help.
How can I get the ID or what is necessary of a specific todo item to edit this one?

**Comment by tobixen** [comment]
Two ways ... you can either use any other filtering option to select a list of tasks or a single task (use --limit=1 and --offsetn=x) and then edit (or, eventually, complete, delete, postpone or whatever) on that item or those items ...

    $ ./calendar-cli todo --offsetn=3 --limit=1 --categories=housework list
    2019-01-25 (Fri) 2019-01-26 (Wed) clean the fridge
    $ ./calendar-cli todo --offsetn=3 --limit=1 complete

Or use the --todo-template to find the uids

    calendar-cli todo list --todo-template='{uid} {summary}' | grep -i 'clean'

and then ...

    calendar-cli --todo-uid=2bfc15a8-d9a8-11e6-9ccc-9c8e99d15218 edit --add-categories housework

This is a command line interface, not a text user interface - but eventually the EXAMPLE file suggests using  the todo-template to generate calendar-cli-commands and then use an editor to edit those.  Probably one will be better off using some more proper user interface.
