### ISSUE TITLE
Date_search expand

### ISSUE THREAD

**Issue by guyotv** [tobixen/calendar-cli#61]
Hi,
Excuse-me for my bad english. Thank you very much for your soft which is exactly I search.
I had a problem when I tried the following line : `calendar-cli.py calendar agenda --from-time=2016-05-17 --agenda-days=14`.
Error was :
`File "/usr/local/bin/calendarcmd", line 480, in calendar_agenda events_ = find_calendar(caldav_conn, args).date_search(dtstart, dtend, expand=True) TypeError: date_search() got an unexpected keyword argument 'expand'`
I removed ", expand=True" at line 480 and the error disappeared and all worked out.
But, is it correct to do so ?
Thank you again for your work. Have a nice day. Vincent

**Comment by tobixen** [comment]
The problem is most likely due to the wrong version of caldav library being used.  Try to upgrade the caldav library.  The most recent version is 0.6.2.  Please reopen the issue if that won't help.

**Comment by guyotv** [comment]
Hi,
Thank you for your response.
I use Debian 10 and I installed python-caldav, which is in version 0.5.0-0.1 indeed. But, Debian 10 is the last version of this distribution and install another version is probably not recommended ? But without expand, all seems ok and if I wait the next version of Debian, is it a problem ?
Have a nice day and thank you again.

**Comment by tobixen** [comment]
To install the latest version of the caldav library, you can probably do "sudo pip install caldav" or "sudo easy install caldav".
