### ISSUE TITLE
Delete by date

### ISSUE THREAD

**Issue by guyotv** [tobixen/calendar-cli#62]
Hi,
I haven't found how delete an event. At the end of your code, I found arguments --event-uid, -url and -timestamp. I try uid and it works fine. But, with -timestamp, not. Is there a little documentation for the format of timestamp or is it evident ? It's certainly not a criticism, just a question.
Thank you. Vincent
(My english is poor. In frech, I know that words are important to say I only search to use a work I appreciate, but in english, i don't know how to say that.)

**Comment by tobixen** [comment]
The delete-by-timestamp feature was never implemented.  I'm not sure if delete-by-timestamp is really needed?

delete-by-uid is perhaps not good enough as "standard" usage of the calendar-cli tool does not show the uid.

I did things differently when I implemented the task list support.  In the future I will consolidate the calendar and task list code, and make it possible to delete calendar events in the same way as tasks.

**Comment by guyotv** [comment]
Ok, and if I understood correctly, you have choice (and for me it's a good choice) not to memorize uid localy with date. But, without a local file, how to memorize uid ? In the calendar ?

Ps. I answered my other issue, but I don't know how reopen it ?

**Comment by tobixen** [comment]
Sorry for the slow reply on this one, it fell through the cracks.

To get out the uids from the calendar, it's possible to use the --event-template option.  The default is "{dtstart} {summary}" and it's possible to add {uid} to it.

Follow-up items:

* documentation needs to be improved (I'll follow up with a separate task for that)
* The delete-by-timestamp should be removed, as it doesn't work - or I should fix it to work - but I think I'll fix some solution when dealing with #12
