### ISSUE TITLE
Feature: add a private event

### ISSUE THREAD

**Issue by bug** [tobixen/calendar-cli#76]
It would be nice to be able to add an event to a calendar as a private event.

**Comment by tobixen** [comment]
I think the icalendar standard has some attributes for "confidential" events, but I have no experience with it. What kind of caldav server do you use?

**Comment by bug** [comment]
We have a zimbra suite with its caldav server. I managed to create private events simply by adding a class private attribute to the event:

    --- a/calendar-cli.py
    +++ b/calendar-cli.py
    @@ -350,6 +350,8 @@ def calendar_add(caldav_conn, args):
             event.add('dtstart', dtstart)
             ## TODO: handle duration and end-time as options.  default 3600s by now.
             event.add('dtend', dtstart + timedelta(0,event_duration_secs))
    +    if (args.private):
    +        event.add('class', 'PRIVATE')
         event.add('dtstamp', _now())
         uid = uuid.uuid1()
         event.add('uid', str(uid))
    @@ -910,6 +912,7 @@ def main():
         calendar_add_parser.add_argument('summary', nargs='+')
         calendar_add_parser.set_defaults(func=calendar_add)
         calendar_add_parser.add_argument('--whole-day', help='Whole-day event', action='store_true', default=False)
    +    calendar_add_parser.add_argument('--private', help='Private event', action='store_true', default=False)
 
         for attr in vcal_txt_one + vcal_txt_many:
             calendar_add_parser.add_argument('--set-'+attr, help='Set '+attr)

I have no other caldav server I could test against.

**Comment by tobixen** [comment]
Can you make that into a pull request? I'm not by a keyboard at the moment

**Comment by bug** [comment]
Implemented in #77
